/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen_labprograii_iparcial;

import java.awt.Color;

/**
 *
 * @author Gabriela Mejia
 */
public class VerPerfil extends javax.swing.JFrame {

    /**
     * Creates new form VerPerfil
     */
    UberSocial uber;
    String username;

    public VerPerfil(UberSocial uber, String username) {
        initComponents();
        this.uber = uber;
        this.username = username;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Color backgroundColor = new Color(245, 234, 240);
        getContentPane().setBackground(backgroundColor);
        updateProfile();
    }

    private void updateProfile() {
        SocialClass account = uber.buscar(username);
        if (account != null) {
            txtAPerfil.setText("");
            txtAPerfil.append("Username: " + account.username + "\n\n");
            txtAPerfil.append("Posts:\n");
            for (String post : account.posts) {
                txtAPerfil.append("- " + post + "\n");
            }
        } else {
            txtAPerfil.setText("Usuario no encontrado.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAPerfil = new javax.swing.JTextArea();
        lblPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAPerfil.setEditable(false);
        txtAPerfil.setColumns(20);
        txtAPerfil.setRows(5);
        jScrollPane1.setViewportView(txtAPerfil);

        lblPerfil.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblPerfil.setText("Mi Perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblPerfil)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblPerfil)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JTextArea txtAPerfil;
    // End of variables declaration//GEN-END:variables
}
